#pragma once

// Base class for
//
//

#include <string>
#include <vector>
#include <iostream>

#include "globals.cuh"

// Class generated by GPGPUAudioCodegen.
// Feel free to edit any code. Suggested first edit is to replace this message with your own class comment.
//   -Code *outside* the tags styled like "<GPUA_GENERATED>"  will not be replaced on future invocations,
//    unless you happen to use one of the template tokens (not likely, but not supported).
//   -Code inside the <GPUA_GENERATED> tags *will* be replaced on future invocations.
//    This allows you to resize buffers etc.
class
__gpuagen.tok.NAME {
public:
	__gpuagen.tok.NAME() = default;
	~__gpuagen.tok.NAME() = default;

	// Empty interface; subclasses can specialize.
	virtual void run(RunData& runData) = 0;

	void InitDefaultBuffers();

	protected:
__gpuagen.tok.BUFFER_HEADER
};